---
- import_playbook: pbVyos.yml
- import_playbook: pbClientConfigureIp.yml
- import_playbook: pbServerDocker.yml
- import_playbook: pbCloudUser.yml
- import_playbook: pbSe.yml
- import_playbook: pbSeGroup.yml
- import_playbook: pbIpamDns.yml
- import_playbook: pbCloud.yml
- import_playbook: pbVrf.yml
- import_playbook: pbVs.yml
