---
- hosts: localhost
  connection: local

  vars_files:
    # - "vars/creds.json"
    - "vars/params.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Create a Cloud connector user
      avi_cloudconnectoruser:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        api_context: "{{ avi_api_context | default(omit) }}"
        private_key: "{{ lookup('file', '{{ cloudconnectoruser.private_key }}') }}"
        name: "{{ cloudconnectoruser.name }}"
      ignore_errors: no
