---
- hosts: localhost
  connection: local

  vars_files:
    - "vars/creds.json"
    - "vars/params.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Gather cluster uuid
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: cluster
        tenant: "{{ tenant | default('admin') }}"
      register: statusCluster

    - name: Debug
      debug:
        msg: "{{ statusCluster.obj.uuid }}"
      tags:
        - debug

    - name: Enable the GSLB config with the leader cluster
      avi_gslb:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        name: "Default"
        leader_cluster_uuid: "{{ statusCluster.obj.uuid }}"
        sites: "{{ avi_gslb.sites }}"
        dns_configs: "{{ dns_configs }}"
      # loop: "{{ avi_gslb }}"
      # loop_control:
      #   label: "{{ item.name }}"
      tags:
        - infraGslb


    #
    # Geo loc requires 8 GB of Memory
    #
    # - name: Enable GSLB profile
    #   avi_gslbgeodbprofile:
    #     avi_credentials: "{{ avi_credentials }}"
    #     api_version: "{{ avi_credentials.api_version }}"
    #     tenant: "{{ item.tenant_ref | default('admin') }}"
    #     tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
    #     name: "{{ item.name }}"
    #     entries: "{{ item.entries }}"
    #   loop: "{{ avi_gslbgeodbprofile }}"
    #   tags:
    #     - geo
