
---
- hosts: controller
  connection: local

  vars_files:
    - "vars/creds.json"
    - "vars/params.yml"

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Modify/creating SE group
      avi_serviceenginegroup:
        avi_api_update_method: put
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        ha_mode: "{{ item.ha_mode }}"
        min_scaleout_per_vs: "{{ item.min_scaleout_per_vs }}"
        buffer_se: "{{ item.buffer_se }}"
      loop: "{{ serviceEngineGroup }}"
      loop_control:
        label: "Modifying SE group called {{ item.name }}"
