---
- name: vyos
  connection: network_cli
  gather_facts: false
  hosts: vyos

  vars_files:
  - "vars/params.yml"


  tasks:

    - name: backup and load from file
      vyos_config:
        src: "{{ vyOSConfig }}"
        save: yes

    - name: reboot the VyOS router
      vyos_command:
        commands:
          - command: 'reboot now'
