---

avi_systemconfiguration:
  global_tenant_config:
    se_in_provider_context: true
    tenant_access_to_provider_se: true
    tenant_vrf: true
  welcome_workflow_complete: true
  ntp_configuration:
    ntp_servers:
      - server:
          type: V4
          addr: 192.168.10.3
  dns_configuration:
    search_domain: ''
    server_list:
      - type: V4
        addr: 8.8.8.8
      - type: V4
        addr: 4.4.4.4
  email_configuration:
    from_email: test@avicontroller.net
    smtp_type: SMTP_LOCAL_HOST

cloudconnectoruser:
  name: avi
  private_key: /home/avi/.ssh/id_rsa

dns:
  name: dns-avi
  domain:
    name: lsc.avidemo.fr

network:
  name: net-avi
  dhcp_enabled: no
  subnet:
    - prefix:
        mask: 24
        ip_addr:
          type: V4
          addr: 10.1.2.0
      static_ranges:
        - begin:
            type: V4
            addr: 10.1.2.51
          end:
            type: V4
            addr: 10.1.2.100



ipam:
  name: ipam-avi
#  network: 0

cloud:
  tenant_ref: admin
  dns_provider_ref: dns-avi
  ipam_provider_ref: ipam-avi
  se:
    cpu: 1
    mem: 1
    dpdk: 'No'
    se_inband_mgmt: False
    se_group_ref: Default-Group
    # addr: 192.168.17.153

vrfcontext:
  - name: global
    gw:
    - gateway_monitor_success_threshold: 15
      gateway_ip:
        type: V4
        addr: 10.1.2.1
      gateway_monitor_fail_threshold: 10
      gateway_monitor_interval: 1000
    bgp_profile:
      peers:
      - keepalive_interval: 1
        subnet:
          mask: 24
          ip_addr:
            type: V4
            addr: 10.1.2.0
        remote_as: 200
        ebgp_multihop: 0
        bfd: false
        advertise_snat_ip: true
        connect_timer: 10
        peer_ip:
          type: V4
          addr: 10.1.2.1
        advertise_vip: true
        advertisement_interval: 5
        shutdown: false
        hold_time: 3
      local_as: 100
      ibgp: false
      send_community: true
      shutdown: false
      hold_time: 180


avi_applicationprofile:
  - name: appProfileNic

avi_healthmonitor:
  - name: &hm0 hm1
    receive_timeout: 1
    failed_checks: 2
    send_interval: 1
    successful_checks: 2
    type: HEALTH_MONITOR_HTTP
    http_request: "HEAD / HTTP/1.0"
    http_response_code:
      - HTTP_2XX
      - HTTP_3XX
      - HTTP_5XX

# avi_pool:
#   - name: pool1
#     lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
#     health_monitor_refs: hm1
#     servers:
#       - ipaddr: 172.16.3.253
#         iptype: 'V4'
#       - ipaddr: 172.16.3.254
#         iptype: 'V4'
#   - name: pool2
#     lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
#     health_monitor_refs: hm1
#     servers:
#       - ipaddr: 172.16.3.251
#         iptype: 'V4'
#       - ipaddr: 172.16.3.252
#         iptype: 'V4'

avi_pool:
  - name: &pool0 pool1
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    health_monitor_refs: *hm0
    servers:
      - ip:
          addr: 172.16.3.253
          type: 'V4'
      - ip:
          addr: 172.16.3.254
          type: 'V4'
  - name: &pool1 pool2
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    health_monitor_refs: *hm0
    servers:
      - ip:
          addr: 172.16.3.251
          type: 'V4'
      - ip:
          addr: 172.16.3.252
          type: 'V4'

avi_virtualservice:
  dns:
    - name: &vs0 app1-dns
      port: 53
      #vip: 10.1.2.50
      enable_rhi: false
      application_profile_ref: System-DNS
      network_profile_ref: System-UDP-Per-Pkt
  http:
    - name: &vs1 app2
      # port: 80
      services:
        - port: 80
          enable_ssl: false
        - port: 443
          enable_ssl: true
      pool_ref: *pool0
      enable_rhi: false
      # network_ref: net-avi
      # mask: 24
      # type: V4
      # addr: 10.1.2.0
      # # fqdn: vs2.demoavi.local
    - name: &vs2 app3
      # port: 80
      services:
        - port: 443
          enable_ssl: true
      pool_ref: *pool1
      enable_rhi: false
      # network_ref: net-avi
      # mask: 24
      # type: V4
      # addr: 10.1.2.0
      # fqdn: vs3.demoavi.local

# avi_vsvip:
#   - name: *vs0
#     network_ref: "{{ networkName }}"
#     mask: "{{ networkMask }}"
#     type: "{{ networkType }}"
#     addr: "{{ networkAddress }}"
#   - name: *vs1
#     network_ref: "{{ networkName }}"
#     mask: "{{ networkMask }}"
#     type: "{{ networkType }}"
#     addr: "{{ networkAddress }}"
#   - name: *vs2
#     network_ref: "{{ networkName }}"
#     mask: "{{ networkMask }}"
#     type: "{{ networkType }}"
#     addr: "{{ networkAddress }}"

avi_gslb:
  sites:
    - username: "{{ avi_credentials.username }}"
      password: "{{ avi_credentials.password }}"
      cluster_uuid: "{{ statusCluster.obj.uuid }}"
      member_type: GSLB_ACTIVE_MEMBER
      name: "local_controller"
      ip_addresses:
        - type: "V4"
          addr: "{{ avi_credentials.controller }}"
      dns_vses:
      - domain_names:
        - "{{ dns_configs.0.domain_name }}"
        dns_vs_uuid: "{{ OutputVsDns.results.0.obj.uuid }}"

dns_configs:
  - domain_name: gslb.avidemo.fr

avi_gslbgeodbprofile:
  - name: geoProfile
    entries:
      - priority: 10
        file:
          #timestamp: 1595599889
          #checksum: 18751e4db1f32a49f2a8be157218f2e2078734c20f8f39b0839a3e951e858d20
          format: GSLB_GEODB_FILE_FORMAT_AVI
          #file_id: AviGeoDb.txt.gz_1595599889.gz
          filename: AviGeoDb.txt.gz

avi_gslbservice:
  - name: *vs1
    groups:
    - priority: 10
      members:
      - ratio: 1
        ip:
          type: "{{ OutputVsHttpVip.results.0.obj.vip.0.ip_address.type }}"
          addr: "{{ OutputVsHttpVip.results.0.obj.vip.0.ip_address.addr }}"
        enabled: true
        vs_uuid: "{{ OutputVsHttp.results.0.obj.uuid }}"
        cluster_uuid: "{{ statusCluster.obj.uuid }}"
        resolve_fqdn_to_v6: false
      enabled: true
      name: lsc
      algorithm: GSLB_ALGORITHM_ROUND_ROBIN
    site_persistence_enabled: false
    min_members: 0
    health_monitor_scope: GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS
    pool_algorithm: GSLB_SERVICE_ALGORITHM_GEO
  - name: *vs2
    groups:
    - priority: 10
      members:
      - ratio: 1
        ip:
          type: "{{ OutputVsHttpVip.results.1.obj.vip.0.ip_address.type }}"
          addr: "{{ OutputVsHttpVip.results.1.obj.vip.0.ip_address.addr }}"
        enabled: true
        vs_uuid: "{{ OutputVsHttp.results.1.obj.uuid }}"
        cluster_uuid: "{{ statusCluster.obj.uuid }}"
        resolve_fqdn_to_v6: false
      enabled: true
      name: lsc
      algorithm: GSLB_ALGORITHM_ROUND_ROBIN
    site_persistence_enabled: false
    min_members: 0
    health_monitor_scope: GSLB_SERVICE_HEALTH_MONITOR_ALL_MEMBERS
    pool_algorithm: GSLB_SERVICE_ALGORITHM_GEO
