---
cloudconnectoruser:
  name: avi
  private_key: /home/avi/.ssh/id_rsa

dns:
  name: dns-avi
  domain:
    name: demoavi.local

network:
  name: net-avi
  dhcp_enabled: no
  subnet:
    - prefix:
        mask: 24
        ip_addr:
          type: V4
          addr: 10.1.2.0
      static_ranges:
        - begin:
            type: V4
            addr: 10.1.2.51
          end:
            type: V4
            addr: 10.1.2.100



ipam:
  name: ipam-avi
#  network: 0

serviceEngineGroup:
  - name: Default-Group
    ha_mode: HA_MODE_SHARED # N+M
    min_scaleout_per_vs: 2 # required for active active
    buffer_se: 0
  - name: dev-Group
    ha_mode: HA_MODE_SHARED # N+M
    min_scaleout_per_vs: 1 # required for active standby
    buffer_se: 0


cloud:
  tenant_ref: admin
  dns_provider_ref: dns-avi
  ipam_provider_ref: ipam-avi
  se:
    cpu: 1
    mem: 1
    dpdk: 'No'
    se_inband_mgmt: False
    se_group_ref:
      - Default-Group
      - dev-Group
    # addr: 192.168.17.153

vrfcontext:
  - name: global
    gw:
    - gateway_monitor_success_threshold: 15
      gateway_ip:
        type: V4
        addr: 10.1.2.1
      gateway_monitor_fail_threshold: 10
      gateway_monitor_interval: 1000
    bgp_profile:
      peers:
      - keepalive_interval: 1
        subnet:
          mask: 24
          ip_addr:
            type: V4
            addr: 10.1.2.0
        remote_as: 200
        ebgp_multihop: 0
        bfd: false
        advertise_snat_ip: true
        connect_timer: 10
        peer_ip:
          type: V4
          addr: 10.1.2.1
        advertise_vip: true
        advertisement_interval: 5
        shutdown: false
        hold_time: 3
      local_as: 100
      ibgp: false
      send_community: true
      shutdown: false
      hold_time: 180

avi_healthmonitor:
  - name: hm1
    receive_timeout: 1
    failed_checks: 2
    send_interval: 1
    successful_checks: 2
    type: HEALTH_MONITOR_HTTP
    http_request: "HEAD / HTTP/1.0"
    http_response_code:
      - HTTP_2XX
      - HTTP_3XX
      - HTTP_5XX

# avi_pool:
#   - name: pool1
#     lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
#     health_monitor_refs: hm1
#     servers:
#       - ipaddr: 172.16.3.253
#         iptype: 'V4'
#       - ipaddr: 172.16.3.254
#         iptype: 'V4'
#   - name: pool2
#     lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
#     health_monitor_refs: hm1
#     servers:
#       - ipaddr: 172.16.3.251
#         iptype: 'V4'
#       - ipaddr: 172.16.3.252
#         iptype: 'V4'

avi_pool:
  - name: pool1
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    health_monitor_refs: hm1
    servers:
      - ip:
          addr: 172.16.3.253
          type: 'V4'
      - ip:
          addr: 172.16.3.254
          type: 'V4'
  - name: pool2
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    health_monitor_refs: hm1
    servers:
      - ip:
          addr: 172.16.3.251
          type: 'V4'
      - ip:
          addr: 172.16.3.252
          type: 'V4'

virtualservice:
  dns:
    - name: vs1-dns
      port: 53
      vip: 10.1.2.50
      enable_rhi: false
      application_profile_ref: System-DNS
      network_profile_ref: System-UDP-Per-Pkt
      se_group_ref: Default-Group
  http:
    - name: vs2-http
      # port: 80
      services:
        - port: 80
          enable_ssl: false
        - port: 443
          enable_ssl: true
      pool_ref: pool1
      enable_rhi: false
      network_ref: net-avi
      mask: 24
      type: V4
      addr: 10.1.2.0
      fqdn: vs2.demoavi.local
      se_group_ref: dev-Group
    - name: vs3-https
      # port: 80
      services:
        - port: 443
          enable_ssl: true
      pool_ref: pool2
      enable_rhi: false
      network_ref: net-avi
      mask: 24
      type: V4
      addr: 10.1.2.0
      fqdn: vs3.demoavi.local
      se_group_ref: Default-Group

  # https:
  #   - name: vs3-https
  #     services:
  #       - port: 443
  #         enable_ssl: true
  #     #enable_ssl: true
  #     #port: 443
  #     pool_ref: pool2
  #     fqdn: vs3.demoavi.local
  #     ssl_profile_ref: System-Standard
  #     ssl_key_and_certificate_refs: System-Default-Cert

ipClient:
  - iface: ens33
    cidr: 10.1.2.2/24

ipServer:
  - iface: ens34
    cidr: 172.16.3.251/24
  - iface: ens34
    cidr: 172.16.3.252/24
  - iface: ens34
    cidr: 172.16.3.253/24
  - iface: ens34
    cidr: 172.16.3.254/24

docker:
  - name: web1
    image: tacobayle/web1
  - name: web2
    image: tacobayle/web2
  - name: web3
    image: tacobayle/web3
  - name: web4
    image: tacobayle/web4
