---
cloudconnectoruser:
  name: avi
  private_key: /home/avi/.ssh/id_rsa

dns:
  name: dns-avi
  domain:
    name: lsc.avidemo.fr

network:
  name: net-avi
  dhcp_enabled: no
  subnet:
    - prefix:
        mask: 24
        ip_addr:
          type: V4
          addr: 5.5.5.0
      static_ranges:
        - begin:
            type: V4
            addr: 5.5.5.51
          end:
            type: V4
            addr: 5.5.5.100



ipam:
  name: ipam-avi

serviceEngineGroup:
  - name: Default-Group
    ha_mode: HA_MODE_SHARED # N+M
    min_scaleout_per_vs: 2 # required for acitive active
    buffer_se: 0

cloud:
  tenant_ref: admin
  dns_provider_ref: dns-avi
  ipam_provider_ref: ipam-avi
  se:
    cpu: 1
    mem: 1
    dpdk: 'No'
    se_inband_mgmt: False
    se_group_ref: Default-Group

vrfcontext:
  - name: global
    bgp_profile:
      peers:
      - keepalive_interval: 1
        subnet:
          mask: 24
          ip_addr:
            type: V4
            addr: 10.1.2.0
        remote_as: 200
        ebgp_multihop: 0
        bfd: false
        advertise_snat_ip: true
        connect_timer: 10
        peer_ip:
          type: V4
          addr: 10.1.2.1
        advertise_vip: true
        advertisement_interval: 5
        shutdown: false
        hold_time: 3
      local_as: 100
      ibgp: false
      send_community: true
      shutdown: false
      hold_time: 180

avi_healthmonitor:
  - name: hm1
    receive_timeout: 1
    failed_checks: 2
    send_interval: 1
    successful_checks: 2
    type: HEALTH_MONITOR_HTTP
    http_request: "HEAD / HTTP/1.0"
    http_response_code:
      - HTTP_2XX
      - HTTP_3XX
      - HTTP_5XX

avi_pool:
  - name: pool1
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    health_monitor_refs: hm1
    servers:
      - ip:
          addr: 172.16.3.253
          type: 'V4'
      - ip:
          addr: 172.16.3.254
          type: 'V4'
  - name: pool2
    lb_algorithm: LB_ALGORITHM_ROUND_ROBIN
    health_monitor_refs: hm1
    servers:
      - ip:
          addr: 172.16.3.251
          type: 'V4'
      - ip:
          addr: 172.16.3.252
          type: 'V4'

virtualservice:
  dns:
    - name: vs-dns
      port: 53
      vip: 5.5.5.50
      enable_rhi: true
      application_profile_ref: System-DNS
      network_profile_ref: System-UDP-Per-Pkt
  http:
    - name: vs1-http
      services:
        - port: 80
          enable_ssl: false
        - port: 443
          enable_ssl: true
      pool_ref: pool1
      enable_rhi: true
      network_ref: net-avi
      mask: 24
      type: V4
      addr: 5.5.5.0
      fqdn: vs2.lsc.avidemo.fr
    - name: vs2-https
      services:
        - port: 443
          enable_ssl: true
      pool_ref: pool2
      enable_rhi: true
      network_ref: net-avi
      mask: 24
      type: V4
      addr: 5.5.5.0
      fqdn: vs3.lsc.avidemo.fr


vyOSConfig: vyos.conf

ipClient:
  - iface: ens33
    cidr: 10.1.4.2/24
  - iface: ens33
    cidr: 10.1.4.3/24
  - iface: ens33
    cidr: 10.1.4.4/24

ipServer:
  - iface: ens34
    cidr: 172.16.3.251/24
  - iface: ens34
    cidr: 172.16.3.252/24
  - iface: ens34
    cidr: 172.16.3.253/24
  - iface: ens34
    cidr: 172.16.3.254/24

routes:
  - cidr: 5.5.5.0/24
    nexthop: 10.1.4.1

docker:
  - name: web1
    image: tacobayle/web1
  - name: web2
    image: tacobayle/web2
  - name: web3
    image: tacobayle/web3
  - name: web4
    image: tacobayle/web4
